#baseURL = "http://localhost:1313/"
baseURL = "https://Meeta-factor.github.io/"
languageCode = "zh-cn"
title = "Meta的工程日志"
theme = "PaperMod"
[markup.goldmark.renderer]
  unsafe = true

[server]
enableCORS = true

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  math = true
  mermaid = true
  customCSS = ["css/extended/custom.css"]
  ShowToc = true
  TocOpen = true

[params.profileMode]
  enabled = true
  title = "Meta的工程日志"
  subtitle = "控制 · 嵌入式 · 系统思考"
  imageUrl = "/images/home.jpg"
  imageTitle = "control"
  imageWidth = 120
  imageHeight = 120
  buttons = [
    { name = "Control", url = "/control/" },
    { name = "Embedded", url = "/embedded/" },
    { name = "Math", url = "/math/" },
    { name = "Thinking", url = "/thinking/" },
    { name = "Posts", url = "/posts/" }
  ]

[params.assets]
  disableHLJS = true


[menu]

  [[menu.main]]
    name = "Control"
    url = "/control/"
    weight = 1

  [[menu.main]]
    name = "Embedded"
    url = "/embedded/"
    weight = 2

  [[menu.main]]
    name = "Math"
    url = "/math/"
    weight = 3

  [[menu.main]]
    name = "Thinking"
    url = "/thinking/"
    weight = 4
  
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 5

